export const INTIALIZE_CALENDER = 'INTIALIZE_CALENDER'
export const INCREASE_MONTH = 'INCREASE_MONTH'
export const DECREASE_MONTH = 'DECREASE_MONTH'
export const CHANGE_EDITING_STATUS_TO_TRUE = 'CHANGE_EDITING_STATUS_TO_TRUE';
export const CHANGE_EDITING_STATUS_TO_FALSE = 'CHANGE_EDITING_STATUS_TO_FALSE'
export const CHANGE_FORM_DATA  = 'CHANGE_FORM_DATA'
export const GET_DAY_SCHEDULES = "GET_DAY_SCHEDULES"


export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const REMOVE_SCHEDULE = 'REMOVE_SCHEDULE'
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE' 

export const SEARCH_TEACHER_SCHEDULES = 'SEARCH_TEACHER_SCHEDULES'
export const REMOVE_SEARCH_RESULTS = 'REMOVE_SEARCH_RESULTS'